(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},n="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},ca=ba(this),p=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var g=a[d];if(!(g in c))break a;c=c[g]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&n(c,a,{configurable:!0,writable:!0,value:b})}};
p("Symbol",function(a){if(a)return a;var b=function(h,m){this.h=h;n(this,"description",{configurable:!0,writable:!0,value:m})};b.prototype.toString=function(){return this.h};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,g=function(h){if(this instanceof g)throw new TypeError("Symbol is not a constructor");return new b(c+(h||"")+"_"+d++,h)};return g});
p("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&n(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},q=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},ea="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ka=fa,r=function(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.G=b.prototype},la=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b},t=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
p("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)t(b,d)&&c.push(b[d]);return c}});p("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});p("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var g=d.length;c=c||0;for(0>c&&(c=Math.max(c+g,0));c<g;c++){var h=d[c];if(h===b||Object.is(h,b))return!0}return!1}});
p("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(b,c||0)}});
p("WeakMap",function(a){function b(){}function c(f){var k=typeof f;return"object"===k&&null!==f||"function"===k}function d(f){if(!t(f,h)){var k=new b;n(f,h,{value:k})}}function g(f){var k=Object[f];k&&(Object[f]=function(l){if(l instanceof b)return l;Object.isExtensible(l)&&d(l);return k(l)})}if(function(){if(!a||!Object.seal)return!1;try{var f=Object.seal({}),k=Object.seal({}),l=new a([[f,2],[k,3]]);if(2!=l.get(f)||3!=l.get(k))return!1;l.delete(f);l.set(k,4);return!l.has(f)&&4==l.get(k)}catch(C){return!1}}())return a;
var h="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var m=0,e=function(f){this.h=(m+=Math.random()+1).toString();if(f){f=q(f);for(var k;!(k=f.next()).done;)k=k.value,this.set(k[0],k[1])}};e.prototype.set=function(f,k){if(!c(f))throw Error("Invalid WeakMap key");d(f);if(!t(f,h))throw Error("WeakMap key fail: "+f);f[h][this.h]=k;return this};e.prototype.get=function(f){return c(f)&&t(f,h)?f[h][this.h]:void 0};e.prototype.has=function(f){return c(f)&&t(f,h)&&t(f[h],this.h)};
e.prototype.delete=function(f){return c(f)&&t(f,h)&&t(f[h],this.h)?delete f[h][this.h]:!1};return e});
p("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var e=Object.seal({x:4}),f=new a(q([[e,"s"]]));if("s"!=f.get(e)||1!=f.size||f.get({x:4})||f.set({x:4},"t")!=f||2!=f.size)return!1;var k=f.entries(),l=k.next();if(l.done||l.value[0]!=e||"s"!=l.value[1])return!1;l=k.next();return l.done||4!=l.value[0].x||"t"!=l.value[1]||!k.next().done?!1:!0}catch(C){return!1}}())return a;var b=new WeakMap,c=function(e){this.i={};this.h=h();
this.size=0;if(e){e=q(e);for(var f;!(f=e.next()).done;)f=f.value,this.set(f[0],f[1])}};c.prototype.set=function(e,f){e=0===e?0:e;var k=d(this,e);k.list||(k.list=this.i[k.id]=[]);k.j?k.j.value=f:(k.j={next:this.h,s:this.h.s,head:this.h,key:e,value:f},k.list.push(k.j),this.h.s.next=k.j,this.h.s=k.j,this.size++);return this};c.prototype.delete=function(e){e=d(this,e);return e.j&&e.list?(e.list.splice(e.index,1),e.list.length||delete this.i[e.id],e.j.s.next=e.j.next,e.j.next.s=e.j.s,e.j.head=null,this.size--,
!0):!1};c.prototype.clear=function(){this.i={};this.h=this.h.s=h();this.size=0};c.prototype.has=function(e){return!!d(this,e).j};c.prototype.get=function(e){return(e=d(this,e).j)&&e.value};c.prototype.entries=function(){return g(this,function(e){return[e.key,e.value]})};c.prototype.keys=function(){return g(this,function(e){return e.key})};c.prototype.values=function(){return g(this,function(e){return e.value})};c.prototype.forEach=function(e,f){for(var k=this.entries(),l;!(l=k.next()).done;)l=l.value,
e.call(f,l[1],l[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(e,f){var k=f&&typeof f;"object"==k||"function"==k?b.has(f)?k=b.get(f):(k=""+ ++m,b.set(f,k)):k="p_"+f;var l=e.i[k];if(l&&t(e.i,k))for(e=0;e<l.length;e++){var C=l[e];if(f!==f&&C.key!==C.key||f===C.key)return{id:k,list:l,index:e,j:C}}return{id:k,list:l,index:-1,j:void 0}},g=function(e,f){var k=e.h;return da(function(){if(k){for(;k.head!=e.h;)k=k.s;for(;k.next!=k.head;)return k=k.next,{done:!1,value:f(k)};k=null}return{done:!0,
value:void 0}})},h=function(){var e={};return e.s=e.next=e.head=e},m=0;return c});p("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});var ma=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,g={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};g[Symbol.iterator]=function(){return g};return g};
p("Array.prototype.entries",function(a){return a?a:function(){return ma(this,function(b,c){return[b,c]})}});p("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});p("Array.prototype.values",function(a){return a?a:function(){return ma(this,function(b,c){return c})}});p("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)t(b,d)&&c.push([d,b[d]]);return c}});
var u=this||self,na=function(a,b){a=a.split(".");var c=u;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b},v=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},oa=function(a,b){function c(){}c.prototype=b.prototype;a.G=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.I=function(d,g,h){for(var m=Array(arguments.length-2),e=2;e<
arguments.length;e++)m[e-2]=arguments[e];return b.prototype[g].apply(d,m)}},pa=function(a){return a};var qa=function(a){a=(void 0===a?null:a)||u;return a.googlefc||(a.googlefc={})};var ra={H:"loaded"};function sa(a){return"string"===typeof a&&Object.values(ra).includes(a)};function w(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,w);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}oa(w,Error);w.prototype.name="CustomError";function x(a,b){a=a.split("%s");for(var c="",d=a.length-1,g=0;g<d;g++)c+=a[g]+(g<b.length?b[g]:"%s");w.call(this,c+a[d])}oa(x,w);x.prototype.name="AssertionError";function y(a,b,c,d){var g="Assertion failed";if(c){g+=": "+c;var h=d}else a&&(g+=": "+a,h=b);throw new x(""+g,h||[]);}
var z=function(a,b,c){a||y("",null,b,Array.prototype.slice.call(arguments,2))},ta=function(a,b,c){null==a&&y("Expected to exist: %s.",[a],b,Array.prototype.slice.call(arguments,2));return a},ua=function(a,b){throw new x("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},va=function(a,b,c){"string"!==typeof a&&y("Expected string but got %s: %s.",[v(a),a],b,Array.prototype.slice.call(arguments,2))},wa=function(a,b,c){"function"!==typeof a&&y("Expected function but got %s: %s.",[v(a),
a],b,Array.prototype.slice.call(arguments,2))},A=function(a,b,c){Array.isArray(a)||y("Expected array but got %s: %s.",[v(a),a],b,Array.prototype.slice.call(arguments,2))},ya=function(a,b,c,d){a instanceof b||y("Expected instanceof %s but got %s.",[xa(b),xa(a)],c,Array.prototype.slice.call(arguments,3));return a};
function xa(a){return a instanceof Function?a.displayName||a.name||"unknown type name":a instanceof Object?a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a):null===a?"null":typeof a};var za,B;a:{for(var Aa=["CLOSURE_FLAGS"],D=u,Ba=0;Ba<Aa.length;Ba++)if(D=D[Aa[Ba]],null==D){B=null;break a}B=D}var Ca=B&&B[610401301];za=null!=Ca?Ca:!1;var E,Da=u.navigator;E=Da?Da.userAgentData||null:null;function Ea(a){return za?E?E.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function F(a){var b;a:{if(b=u.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function G(){return za?!!E&&0<E.brands.length:!1}function Fa(){return G()?Ea("Chromium"):(F("Chrome")||F("CriOS"))&&!(G()?0:F("Edge"))||F("Silk")};var Ga=Array.prototype.some?function(a,b){z(null!=a.length);return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,g=0;g<c;g++)if(g in d&&b.call(void 0,d[g],g,a))return!0;return!1};var Ha=G()?!1:F("Trident")||F("MSIE");!F("Android")||Fa();Fa();F("Safari")&&(Fa()||(G()?0:F("Coast"))||(G()?0:F("Opera"))||(G()?0:F("Edge"))||(G()?Ea("Microsoft Edge"):F("Edg/"))||G()&&Ea("Opera"));var Ia={},H=null;var Ja="undefined"!==typeof Uint8Array,Ka=!Ha&&"function"===typeof btoa;var I="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol("INTERNAL_ARRAY_STATE"):void 0;function La(a,b){z((b&255)==b);A(a,"state is only maintained on arrays.");if(I)return a[I]|=b;if(void 0!==a.h)return a.h|=b;Object.defineProperties(a,{h:{value:b,configurable:!0,writable:!0,enumerable:!1}});return b}var Ma=Object.getOwnPropertyDescriptor(Array.prototype,"D");
Object.defineProperties(Array.prototype,{D:{get:function(){function a(g,h){g&b&&c.push(h)}var b=J(this),c=[];a(1,"IS_REPEATED_FIELD");a(2,"IS_IMMUTABLE_ARRAY");a(4,"IS_API_FORMATTED");a(8,"ONLY_MUTABLE_VALUES");a(16,"MUTABLE_REFERENCES_ARE_OWNED");a(32,"CONSTRUCTED");a(64,"TRANSFERRED");a(128,"IS_FIXED_GROUP");var d=c.join(",");return Ma?Ma.get.call(this)+"|"+d:d},configurable:!0,enumerable:!1}});function J(a){A(a,"state is only maintained on arrays.");var b;I?b=a[I]:b=a.h;return null==b?0:b}
function K(a,b){A(a,"state is only maintained on arrays.");z((b&255)==b);I?a[I]=b:void 0!==a.h?a.h=b:Object.defineProperties(a,{h:{value:b,configurable:!0,writable:!0,enumerable:!1}});return a};var Na={};function L(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var Oa,Pa=Object.freeze(K([],23));function Qa(a){if(a&2)throw Error("Cannot mutate an immutable Message");}function Ra(){}function Sa(a){var b=a.length;(b=b?a[b-1]:void 0)&&L(b)?b.g=1:(b={},a.push((b.g=1,b)))};function Ta(a){return a.displayName||a.name||"unknown type name"};var Ua=function(){throw Error("please construct maps as mutable then call toImmutable");};
if("undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance){var Va=function(){throw Error("Cannot perform instanceof checks on ImmutableMap: please use isImmutableMap or isMutableMap to assert on the mutability of a map. See go/jspb-api-gotchas#immutable-classes for more information");},Wa={};Object.defineProperties(Ua,(Wa[Symbol.hasInstance]={value:Va,configurable:!1,writable:!1,enumerable:!1},Wa));z(Ua[Symbol.hasInstance]===Va,"defineProperties did not work: was it monkey-patched?")};var Xa=function(a){var b=a.m+a.i;z(0<=b&&Number.isInteger(b)&&4294967295>b);return a.h||(a.h=a.o[b]={})},Za=function(a,b){Qa(J(a.o));return Ya(a,1,b)},Ya=function(a,b,c){a.v&&(a.v=void 0);if(b>=a.m)return Xa(a)[b]=c,a;a.o[b+a.i]=c;(c=a.h)&&b in c&&delete c[b];return a},$a=function(a,b,c,d){Qa(J(a.o));if(null!=d){if(b=ta(b),!(d instanceof b))throw Error("Expected instanceof "+Ta(b)+" but got "+(d&&Ta(d.constructor)));}else d=void 0;return Ya(a,c,d)};var M;function ab(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a)if(Array.isArray(a)){if(0!==(J(a)&128))return a=Array.prototype.slice.call(a),Sa(a),a}else if(Ja&&null!=a&&a instanceof Uint8Array){if(Ka){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{c=v(a);z("array"==c||"object"==c&&"number"==typeof a.length,"encodeByteArray takes an array as a parameter");
void 0===b&&(b=0);if(!H){H={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");d=["+/=","+/","-_=","-_.","-_"];for(var g=0;5>g;g++){var h=c.concat(d[g].split(""));Ia[g]=h;for(var m=0;m<h.length;m++){var e=h[m],f=H[e];void 0===f?H[e]=m:z(f===m)}}}b=Ia[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(g=h=0;h<a.length-2;h+=3){f=a[h];var k=a[h+1];e=a[h+2];m=b[f>>2];f=b[(f&3)<<4|k>>4];k=b[(k&15)<<2|e>>6];e=b[e&63];c[g++]=""+m+f+k+e}m=0;e=d;switch(a.length-h){case 2:m=a[h+
1],e=b[(m&15)<<2]||d;case 1:a=a[h],c[g]=""+b[a>>2]+b[(a&3)<<4|m>>4]+e+d}a=c.join("")}return a}}return a};function bb(a,b,c,d,g,h){if(null!=a){if(Array.isArray(a))a=g&&0==a.length&&J(a)&1?void 0:h&&J(a)&2?a:cb(a,b,c,void 0!==d,g,h);else if(L(a)){var m={},e;for(e in a)m[e]=bb(a[e],b,c,d,g,h);a=m}else a=b(a,d);return a}}function cb(a,b,c,d,g,h){var m=J(a);d=d?!!(m&16):void 0;a=Array.prototype.slice.call(a);for(var e=0;e<a.length;e++)a[e]=bb(a[e],b,c,d,g,h);c(m,a);return a}function db(a){return a.F===Na?a.toJSON():ab(a)}function eb(a,b){a&128&&Sa(b)};if("undefined"!==typeof Proxy){var N=fb;new Proxy({},{getPrototypeOf:N,setPrototypeOf:N,isExtensible:N,preventExtensions:N,getOwnPropertyDescriptor:N,defineProperty:N,has:N,get:N,set:N,deleteProperty:N,apply:N,construct:N})}function fb(){throw Error("this array or object is owned by JSPB and should not be reused, did you mean to copy it with copyJspbArray? See go/jspb-api-gotchas#construct_from_array");throw Error();};var O=function(a,b,c,d){ya(this,O,"The message constructor should only be used by subclasses");z(this.constructor!==O,"Message is an abstract class and cannot be directly constructed");null==a&&(a=M);M=void 0;var g=this.constructor.i;if(null==a){a=g?[g]:[];var h=48;var m=!0;d&&(h|=128);K(a,h)}else{if(!Array.isArray(a))throw Error("data passed to JSPB constructors must be an Array, got '"+JSON.stringify(a)+"' a "+v(a));if(Object.isFrozen(a)||!Object.isExtensible(a)||Object.isSealed(a))throw Error("data passed to JSPB constructors must be mutable");
if(g&&g!==a[0])throw Error('Expected message to have a message id: "'+g+'" in the array, got: '+JSON.stringify(a[0])+" a "+v(a[0])+", are you parsing with the wrong proto?");h=La(a,0)|32;m=0!==(16&h);if(d){if(h|=128,0<a.length){var e=a[a.length-1];if(L(e)&&"g"in e){delete e.g;var f=!0,k;for(k in e){f=!1;break}f&&a.pop()}}}else if(128&h)throw Error();K(a,h)}this.i=g?0:-1;this.o=a;this.preventPassingToStructuredClone=Ra;a:{h=this.o.length;g=h-1;if(h&&(h=this.o[g],L(h))){this.h=h;this.m=g-this.i;break a}void 0!==
b&&-1<b?(this.m=Math.max(b,g+1-this.i),this.h=void 0):this.m=Number.MAX_VALUE}if(!d&&this.h&&"g"in this.h)throw Error('Unexpected "g" flag in sparse object of message that is not a group type.');if(c){b=m&&!0;d=this.m;var l;for(m=0;m<c.length;m++)g=c[m],g<d?(g+=this.i,(h=a[g])?gb(h,b):a[g]=Pa):(l||(l=Xa(this)),(h=l[g])?gb(h,b):l[g]=Pa)}z(!!(J(this.o)&32))};O.prototype.toJSON=function(){var a=this.o;Oa||(A(a),a=cb(a,db,eb,void 0,!1,!1));return a};
var P=function(a){Oa=!0;try{return JSON.stringify(a.toJSON(),hb)}finally{Oa=!1}};function gb(a,b){if(Array.isArray(a)){var c=J(a),d=1;!b||c&2||(d|=16);(c&d)!==d&&K(a,c|d)}}O.prototype.F=Na;O.prototype.toString=function(){return this.o.toString()};function hb(a,b){return ab(b)};z(!0);function ib(a){if(a instanceof O)return a.constructor.h};(function(){var a=u.jspbGetTypeName;u.jspbGetTypeName=a?function(b){return a(b)||ib(b)}:ib})();var Q=O;function jb(a){return function(b){wa(a);if(null==b||""==b)b=ya(new a,O);else{va(b);b=JSON.parse(b);if(!Array.isArray(b))throw Error("Expected to deserialize an Array but got "+v(b)+": "+b);La(b,16);z(!!(J(b)&16));M=b;b=new a(b);M=void 0}return b}};var R=function(a){Q.call(this,a)};r(R,Q);var kb=jb(R);R.h="tagging.common.regulations.funding_choices.CmpModeObject";var S=function(a){Q.call(this,a,-1,lb)};r(S,Q);var mb=jb(S);S.h="tagging.common.regulations.funding_choices.ExperimentsObject";var lb=[1,2];var nb=function(a){Q.call(this,a)};r(nb,Q);var ob=function(a){var b=new nb;return Za(b,a)};nb.h="tagging.common.regulations.funding_choices.Status";var T=function(a){Q.call(this,a)};r(T,Q);var pb=function(a,b){return $a(a,nb,2,b)};T.prototype.setCmpModeObject=function(a){return $a(this,R,3,a)};T.prototype.setExperimentsObject=function(a){return $a(this,S,5,a)};var qb=jb(T);T.h="tagging.common.regulations.funding_choices.FundingChoicesReturnMessage";var U=function(a,b){this.name=a;this.value=b};U.prototype.toString=function(){return this.name};
var rb=new U("OFF",Infinity),sb=new U("SEVERE",1E3),tb=new U("WARNING",900),ub=new U("CONFIG",700),vb=function(){},wb,xb=function(){},yb=function(a,b){this.h=null;this.v=[];this.i=(void 0===b?null:b)||null;this.m=[];this.l={h:function(){return a}}},zb=function(a){if(a.h)return a.h;if(a.i)return zb(a.i);ua("Root logger has no level set.");return rb},Ab=function(a,b){for(;a;)a.v.forEach(function(c){c(b)}),a=a.i},Bb=function(){this.entries={};var a=new yb("");a.h=ub;this.entries[""]=a},Cb,Db=function(a,
b){var c=a.entries[b];if(c)return c;c=Db(a,b.slice(0,Math.max(b.lastIndexOf("."),0)));var d=new yb(b,c);a.entries[b]=d;c.m.push(d);return d},Eb=function(){Cb||(Cb=new Bb);return Cb},V=function(a){return Db(Eb(),a).l},W=function(a,b,c){var d;if(d=a)if(d=a&&b)b=b.value,d=a?zb(Db(Eb(),a.h())):rb,d=b>=d.value;d&&(a=Db(Eb(),a.h()),"function"===typeof c&&c(),wb||(wb=new vb),c=new xb,Ab(a,c))},X=function(a,b){a&&W(a,tb,b)};var Y=function(){this.i=this.h=null;this.m=!1;this.l=V("boq.contributorservingcommonsharedjs.api.internal.InternalApiManagerImpl")};Y.prototype.setCmpModeObject=function(a){try{this.h=kb(a)}catch(b){(a=this.l)&&W(a,sb,"Failed to deserialize CmpModeObject.")}};Y.prototype.setExperimentsObject=function(a){try{this.i=mb(a)}catch(b){(a=this.l)&&W(a,sb,"Failed to deserialize ExperimentsObject.")}};
Y.prototype.getSerializedReturnMessageForCommand=function(a){if(this.m)return P(pb(new T,ob(4)));switch(a){case "loaded":return P(pb((new T).setCmpModeObject(this.h).setExperimentsObject(this.i),ob(1)));default:return this.getSerializedReturnMessageForInvalidCommand()}};Y.prototype.getSerializedReturnMessageForInvalidCommand=function(){return P(pb(new T,ob(2)))};Y.prototype.setError=function(){this.m=!0};
var Fb=function(a){var b=a.__fcInternalApiManager;if("undefined"!==typeof b)return b;b=new Y;return a.__fcInternalApiManager=b};var Gb=function(a){this.A=new Map;this.C=new Map;this.u=0;this.B=Fb(a);this.l=V("boq.contributorservingcommonsharedjs.api.internal.InternalQueue")};Gb.prototype.push=function(a,b){b=b&&"object"===typeof b&&"function"===typeof b.cb?b.cb:b;if(!sa(a))return a=this.B.getSerializedReturnMessageForInvalidCommand(),Hb(this,b,a),this.u;if(!this.C.get(a)){var c=this.A.get(a)||[];c.push(b);this.A.set(a,c);return this.u}a=this.B.getSerializedReturnMessageForCommand(a);Hb(this,b,a);return this.u};
Gb.prototype.executeCommandType=function(a){if(!sa(a))return this.u;this.C.set(a,!0);for(var b=this.A.get(a)||[];0<b.length;){var c=b.shift();"function"===typeof c&&this.push(a,c)}return this.u};Gb.prototype.executeAllRemainingCommands=function(){for(var a=q(Object.values(ra)),b=a.next();!b.done;b=a.next())this.executeCommandType(b.value);return this.u};
var Hb=function(a,b,c){"function"!==typeof b?(a=a.l)&&W(a,sb,"Callback pushed to InternalQueue is not of type function."):(b(c),a.u++)},Ib=function(a){var b=qa(a).__fci||[];if(!Array.isArray(b))return b;a=new Gb(a);if(0===b.length%2)for(var c=0;c<b.length-1;c+=2)a.push(b[c],b[c+1]);else(b=V("boq.contributorservingcommonsharedjs.api.internal.InternalQueue"))&&W(b,sb,"Odd number of commands pushed to __fci queue. Overriding queue without pushing existing functions.");b=!0;b=void 0===b?!1:b;c=qa(null);
if(!c.hasOwnProperty("__fci")||b)c.__fci=a;return a};var Jb=function(){this.h=window;this.i=null;this.l=V("boq.contributorservingcommonsharedjs.api.internal.InternalApiLoader")};Jb.prototype.load=function(){Ib(this.h);Kb(this)};
var Kb=function(a){a.h.__fcInternalApiPostMessageReady?X(a.l,"postMessage handler already added."):(a.i=function(b){Lb(a,b)},a.h.addEventListener("message",a.i),a.h.__fcInternalApiPostMessageReady=!0)},Lb=function(a,b){var c=b.data.__fciCall;c?"loaded"!==c.command||"number"!==typeof c.callId?X(a.l,"postMessage payload fields are of incorrect type/value."):Ib(a.h).push(c.command,function(d){try{var g=qb(d);var h=Za(g,c.callId)}catch(m){X(a.l,"Failed to deserialize FundingChoicesReturnMessage.");return}d=
{__fciReturn:P(h)};b.source&&"function"===typeof b.source.postMessage&&b.source.postMessage(d,b.origin);return d}):X(a.l,"postMessage had empty payload.")};var Mb;var Z=function(a,b){this.h=a===Nb&&b||"";this.i=Ob};Z.prototype.toString=function(){return"Const{"+this.h+"}"};var Pb=function(a){if(a instanceof Z&&a.constructor===Z&&a.i===Ob)return a.h;ua("expected object of type Const, got '"+a+"'");return"type_error:Const"},Ob={},Nb={};var Rb=function(a,b){this.h=b===Qb?a:""};Rb.prototype.toString=function(){return this.h+""};
var Tb=function(){var a=Sb;if(a instanceof Rb&&a.constructor===Rb)return a.h;ua("expected object of type TrustedResourceUrl, got '"+a+"' of type "+v(a));return"type_error:TrustedResourceUrl"},Qb={},Ub=function(a){if(void 0===Mb){var b=null;var c=u.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:pa,createScript:pa,createScriptURL:pa})}catch(d){u.console&&u.console.error(d.message)}Mb=b}else Mb=b}a=(b=Mb)?b.createScriptURL(a):a;return new Rb(a,Qb)};var Vb=function(){this.h=u.top.document||u.document||document},Wb=function(a){a=a.h;var b="IFRAME";"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};/*

 SPDX-License-Identifier: Apache-2.0
*/
var Xb=[],Yb=function(a){X(V("safevalues"),"A URL with content '"+a+"' was sanitized away.")};-1===Xb.indexOf(Yb)&&Xb.push(Yb);var Sb=Ha?Ub(Pb(new Z(Nb,'javascript:""'))):Ub(Pb(new Z(Nb,"about:blank"))),Zb=function(){this.h=new Vb},ac=function(a,b){if(!$b(a,b)){var c=Wb(a.h);c.name=b;c.src=Tb().toString();c.style.display="none";c.style.width="0px";c.style.height="0px";c.style.border="none";c.style.zIndex="-1000";c.style.left="-1000px";c.style.top="-1000px";var d=function(){a.h.h.body?a.h.h.body.appendChild(c):u.setTimeout(d,5)};d()}},$b=function(a,b){return Ga(a.h.h.getElementsByTagName("IFRAME"),function(c){return c.name===
b})};(function(a,b){u[a]=function(){var c=la.apply(0,arguments);u[a]=function(){};b.apply(null,c)}})("__an6na521li18__",function(a){var b=u.btoa(a+"loader_js"),c=u.btoa(Date.now().toString());na(b,c);a=u.btoa(a+"cached_js");b=u.btoa(Date.now().toString());na(a,b);(new Jb).load();Fb(window).setError();Ib(window).executeAllRemainingCommands();a=new Zb;ac(a,"googlefcInactive");ac(a,"googlefcLoaded")});}).call(this);

__an6na521li18__('');